# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e0a09b622a3541e2dec19a39374405fae032cae210f42f970c0900c17cad34e2d61ca51492cdea9e735d3baf8fdadfc87112e3ef55e43550e5f1c67d81aef051

test:
  secret_key_base: d1e99db76463ef06c86badbcc1fb8bfe829902e6cdf67fd1824aa71bdda7a2ae64f9059975d65b916ed2b5bc97fa551c999f85bf16df04dcc3986af18061d178

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
